name: fp020b
channels:
  - defaults
  - thskaggs
dependencies:
  - python=3.7.*
  - fluxpart=0.2.0b
  - ipython=6.5.*
  - jupyter=1.0.*
  - matplotlib=2.2.*
  - numpy=1.15.*
  - pandas=0.23.*
  - pytest=3.7.*
  - pywavelets=0.5.*
  - attrs=18.*
