name: fluxpart-env
channels:
  - defaults
  - ussl
dependencies:
  - python=3.6
  - fluxpart=0.1.0
  - ipython=6.2.*
  - jupyter=1.0.*
  - matplotlib=2.1.*
  - numpy=1.13.*
  - pytest=3.4.*
  - pywavelets=0.5.*
