{% set name = "fluxpart" %}
{% set version = "0.2.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55df13bf75dde5e9cee07860f11510f87e18cbae4af708ab89a711ab5a6183ca

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - attrs
    - matplotlib
    - numpy
    - pandas
    - pip
    - python
    - pywavelets
  run:
    - attrs
    - matplotlib
    - numpy
    - pandas
    - python
    - pywavelets

test:
  imports:
    - fluxpart
  requires:
    - numpy
    - pandas

about:
  home: https://github.com/usda-ars-ussl/fluxpart
  license: Public Domain CC0
  license_family: CC
  license_file: 
  summary: Module for partitioning eddy covariance flux measurements.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
