{% set name = "fluxpart" %}
{% set version = "0.1.0b2" %}
{% set hash_type = "sha256" %}
{% set hash_value = "0ccddf47d80846f2e7209fb5d52b5b974d0c8c3655086a27c21539d8d30de4c3" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy
    - matplotlib
    - pywavelets
  run:
    - python
    - numpy
    - matplotlib
    - pywavelets

test:
  imports:
    - fluxpart
  requires:
    - numpy

about:
  home: https://github.com/usda-ars-ussl/fluxpart
  license: Public Domain CC0
  license_family: PUBLIC-DOMAIN
  license_file: ''
  summary: Module for partitioning eddy covariance flux measurements.
  description: 'Python 3 module implementing the Scanlon and Sahu (2008) procedure for partitioning eddy covariance measurements of water vapor and carbon dioxide fluxes into stomatal (transpiration, photosynthesis)
    and nonstomatal (evaporation, respiration) components.



    '
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
