{% set name = "fluxpart" %}
{% set version = "0.2.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 15d2e2411cc1f15a33d09c2531b7a5114c75a89ac56d21790586dde8b07a2d12

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - attrs
    - matplotlib
    - numpy
    - pandas
    - pip
    - python
    - pywavelets
  run:
    - attrs
    - matplotlib
    - numpy
    - pandas
    - python
    - pywavelets

test:
  imports:
    - fluxpart
  requires:
    - numpy
    - pandas

about:
  home: "https://github.com/usda-ars-ussl/fluxpart"
  license: Public Domain CC0
  license_family: CC
  license_file: 
  summary: "Module for partitioning eddy covariance flux measurements."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
