{% set name = "fluxpart" %}
{% set version = "0.2.0b" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_rev: v0.2.0b
  git_url: https://github.com/usda-ars-ussl/fluxpart.git

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - numpy
    - matplotlib
    - pandas
    - pywavelets
    - attrs
  run:
    - python
    - numpy
    - matplotlib
    - pandas
    - pywavelets
    - attrs

test:
  imports:
    - fluxpart
  requires:
    - numpy
    - pandas

about:
  home: https://github.com/usda-ars-ussl/fluxpart
  license: Public Domain CC0
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: Module for partitioning eddy covariance flux measurements.
  description: 'Python 3 module implementing the Scanlon and Sahu (2008) procedure for partitioning eddy covariance measurements of water vapor and carbon dioxide fluxes into stomatal (transpiration, photosynthesis) and nonstomatal (evaporation, respiration) components.'
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
