package:
  name: fluxpart
  version: "0.1.0a0"

source:
  fn: fluxpart-0.1.0a0.tar.gz
  url: https://pypi.python.org/packages/f0/3a/ed51e47a4a9cc2a4865a2739cf3ff115c7e7711dcdfc5fadd1c8aa4e720f/fluxpart-0.1.0a0.tar.gz
  md5: e1748f2eb894732e6ac8b3ab8159e391
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - fluxpart = fluxpart:main
    #
    # Would create an entry point called fluxpart that calls fluxpart.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - matplotlib
    - pywavelets

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pywavelets

test:
  # Python imports
  imports:
    - fluxpart

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - numpy
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/usda-ars-ussl/fluxpart
  license: Public Domain CC0
  summary: 'Module for partitioning eddy covariance flux measurements.'
  license_family: PUBLICDOMAIN

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
